version: "3.9"

services:
  database:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wildberries
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql